const fs = require('fs');
const path = require('path');
const base = 'd:/open building/reachinbox-scheduler/backend';

const files = {
    'prisma/schema.prisma': generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "mysql"\n  url      = env("DATABASE_URL")\n}\n\nmodel User {\n  id              String     @id @default(uuid())\n  googleId        String?    @unique\n  email           String     @unique\n  name            String\n  avatar          String?\n  slackWebhookUrl String?\n  createdAt       DateTime   @default(now())\n  senders         Sender[]\n  emailJobs       EmailJob[]\n  campaigns       Campaign[]\n}\n\nmodel Sender {\n  id           String     @id @default(uuid())\n  userId       String\n  email        String\n  etherealUser String?\n  etherealPass String?\n  createdAt    DateTime   @default(now())\n  user         User       @relation(fields: [userId], references: [id])\n  emailJobs    EmailJob[]\n  campaigns    Campaign[]\n}\n\nmodel EmailJob {\n  id             String    @id @default(uuid())\n  userId         String\n  senderId       String\n  campaignId     String?\n  recipientEmail String\n  subject        String\n  body           String    @db.Text\n  scheduledAt    DateTime\n  sentAt         DateTime?\n  status         String    @default("scheduled")\n  idempotencyKey String    @unique\n  bullJobId      String?\n  createdAt      DateTime  @default(now())\n  updatedAt      DateTime  @updatedAt\n  user           User      @relation(fields: [userId], references: [id])\n  sender         Sender    @relation(fields: [senderId], references: [id])\n  campaign       Campaign? @relation(fields: [campaignId], references: [id])\n}\n\nmodel Campaign {\n  id                 String     @id @default(uuid())\n  userId             String\n  senderId           String\n  subject            String\n  body               String     @db.Text\n  delayBetweenEmails Int\n  hourlyLimit        Int\n  startTime          DateTime\n  totalRecipients    Int\n  createdAt          DateTime   @default(now())\n  user               User       @relation(fields: [userId], references: [id])\n  sender             Sender     @relation(fields: [senderId], references: [id])\n  emailJobs          EmailJob[]\n},
    'src/config/prisma.ts': import { PrismaClient } from '@prisma/client';\n\nconst prisma = new PrismaClient();\n\nexport default prisma;,
    'src/queues/emailQueue.ts': import { Queue } from 'bullmq';\nimport { redisConnection } from '../config/redis';\n\nexport const emailQueue = new Queue('email-queue', {\n  connection: redisConnection,\n  defaultJobOptions: {\n    attempts: 3,\n    backoff: {\n      type: 'exponential',\n      delay: 1000,\n    },\n    removeOnComplete: true,\n    removeOnFail: false,\n  },\n});,
    'src/services/emailService.ts': import { v4 as uuidv4 } from 'uuid';\nimport prisma from '../config/prisma';\nimport { emailQueue } from '../queues/emailQueue';\n\nexport const scheduleEmail = async (data: {\n  userId: string;\n  senderId: string;\n  recipientEmail: string;\n  subject: string;\n  body: string;\n  scheduledAt: Date;\n}) => {\n  const idempotencyKey = uuidv4();\n\n  const emailJob = await prisma.emailJob.create({\n    data: {\n      userId: data.userId,\n      senderId: data.senderId,\n      recipientEmail: data.recipientEmail,\n      subject: data.subject,\n      body: data.body,\n      scheduledAt: data.scheduledAt,\n      idempotencyKey,\n      status: 'scheduled',\n    },\n  });\n\n  const delay = Math.max(0, data.scheduledAt.getTime() - Date.now());\n  const bullJob = await emailQueue.add('send-email', { emailJobId: emailJob.id }, { delay });\n\n  return prisma.emailJob.update({\n    where: { id: emailJob.id },\n    data: { bullJobId: bullJob.id },\n  });\n};\n\nexport const getScheduledEmails = async (userId: string) => {\n  return prisma.emailJob.findMany({\n    where: { userId, status: 'scheduled' },\n    orderBy: { scheduledAt: 'asc' },\n  });\n};\n\nexport const getSentEmails = async (userId: string) => {\n  return prisma.emailJob.findMany({\n    where: { userId, status: 'sent' },\n    orderBy: { sentAt: 'desc' },\n  });\n};,
    'src/controllers/emailController.ts': import { Request, Response, NextFunction } from 'express';\nimport * as emailService from '../services/emailService';\n\nconst DUMMY_USER_ID = 'user-1';\nconst DUMMY_SENDER_ID = 'sender-1';\n\nexport const schedule = async (req: Request, res: Response, next: NextFunction): Promise<void> => {\n  try {\n    const { recipientEmail, subject, body, scheduledAt } = req.body;\n    const job = await emailService.scheduleEmail({\n      userId: DUMMY_USER_ID,\n      senderId: DUMMY_SENDER_ID,\n      recipientEmail,\n      subject,\n      body,\n      scheduledAt: new Date(scheduledAt),\n    });\n    res.status(201).json({ success: true, data: job });\n  } catch (error) {\n    next(error);\n  }\n};\n\nexport const listScheduled = async (req: Request, res: Response, next: NextFunction): Promise<void> => {\n  try {\n    const jobs = await emailService.getScheduledEmails(DUMMY_USER_ID);\n    res.json({ success: true, data: jobs });\n  } catch (error) {\n    next(error);\n  }\n};\n\nexport const listSent = async (req: Request, res: Response, next: NextFunction): Promise<void> => {\n  try {\n    const jobs = await emailService.getSentEmails(DUMMY_USER_ID);\n    res.json({ success: true, data: jobs });\n  } catch (error) {\n    next(error);\n  }\n};,
    'src/routes/emailRoutes.ts': import { Router } from 'express';\nimport * as emailController from '../controllers/emailController';\n\nconst router = Router();\n\nrouter.post('/schedule', emailController.schedule);\nrouter.get('/scheduled', emailController.listScheduled);\nrouter.get('/sent', emailController.listSent);\n\nexport default router;,
    'src/routes/index.ts': import { Router } from 'express';\nimport healthRouter from './health';\nimport emailRouter from './emailRoutes';\n\nconst router = Router();\n\nrouter.use('/health', healthRouter);\nrouter.use('/emails', emailRouter);\n\nexport default router;
};

for (const [relativePath, content] of Object.entries(files)) {
    const fullPath = path.join(base, relativePath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content);
    console.log('Created:', relativePath);
}
